"""Init database

Revision ID: 8ee2c0f0d6b7
Revises: 
Create Date: 2022-06-19 23:37:43.850418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import datetime

# revision identifiers, used by Alembic.
from database import UnitType

revision = '8ee2c0f0d6b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_unit',
                    sa.Column('id', postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('date',
                              sa.DateTime(timezone=datetime.timezone.utc),
                              nullable=False),
                    sa.Column('type',
                              sqlalchemy_utils.types.choice.ChoiceType(UnitType,
                                                                       impl=String()),
                              nullable=False),
                    sa.Column('parent_id', postgresql.UUID(as_uuid=True),
                              nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['shop_unit.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_shop_unit_id'), 'shop_unit', ['id'], unique=False)
    op.create_index(op.f('ix_shop_unit_parent_id'), 'shop_unit', ['parent_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_unit_parent_id'), table_name='shop_unit')
    op.drop_index(op.f('ix_shop_unit_id'), table_name='shop_unit')
    op.drop_table('shop_unit')
    # ### end Alembic commands ###
